#!/bin/bash

# Checking if username is root
if [ $EUID -ne 0 ]; then
   	echo "This script must be run as root!" 
   	exit
fi

# Adding programs for install
i=$@

# Checking if argument is empty
if [ -z $@ ]; then
       echo "No argument was entered. Script was closed!"
	   exit 
fi

# Ask about package manager
read -p "Do you use apt or yum: " tool


# Checking if package manager has been entered
if [ -z $tool ]; then
       echo "No user input. Script was closed!"
	   exit  

fi

#Update and Upgrade
echo "Updating and Upgrading packages:"
apt-get update && sudo apt-get upgrade -y

#Installing using apt
if [ $tool = 'apt' ]; then   

    for i
    
	    do

	      sudo apt-get install -y $i

        done

#Installing using yum
elif [ $tool = 'yum' ]; then
     
	  for i
    
	    do

	      sudo yum install -y $i

        done

fi

echo “Installation completed!”
exit